<h1><strong><u>Matrix Computation Assignment</u></strong></h1>

In [1]:
import numpy as np

In [2]:
#Declare vectors and matrices
v = np.array([[1, 2, -1, 3]])
w = np.array([[5], 
              [4], 
              [1],
              [0]])
A = np.array([[1, 0, 1],
              [2, 1, 1],
              [1, -1, 0],
              [0, 0, 2]])
B = np.array([[1, 1, 3, 6],
              [1, -1, 0, 2],
              [0, 0, 1, 3]])


In [3]:
# Problem 1: v + v
solution1 = v + v
print("Problem 1 Solution:\n", solution1)

Problem 1 Solution:
 [[ 2  4 -2  6]]


In [4]:
#Problem 2: 2v
solution2 = 2 * v
print("Problem 2 Solution:\n", solution2)

Problem 2 Solution:
 [[ 2  4 -2  6]]


In [5]:
#Problem 3: v^T + w
solution3 = v.T + w
print("Problem 3 Solution:\n", solution3)

Problem 3 Solution:
 [[6]
 [6]
 [0]
 [3]]


In [6]:
#Problem 4: v + wT
solution4 = v + w.T
print("Problem 4 Solution:\n", solution4)

Problem 4 Solution:
 [[6 6 0 3]]


In [7]:
#Problem 5: v^T - w
solution5 = v.T - w
print("Problem 5 Solution:\n", solution5)

Problem 5 Solution:
 [[-4]
 [-2]
 [-2]
 [ 3]]


In [8]:
#Problem 6: w - v^T
solution6 = w - v.T
print("Problem 6 Solution:\n", solution6)

Problem 6 Solution:
 [[ 4]
 [ 2]
 [ 2]
 [-3]]


In [9]:
#Problem 7: v +2w^T
solution7 = v + (2 * w.T)
print("Problem 7 Solution:\n", solution7)

Problem 7 Solution:
 [[11 10  1  3]]


In [10]:
#Problem 8: v * w^T
solution8 = v * w.T
print("Problem 8 Solution:\n", solution8)

Problem 8 Solution:
 [[ 5  8 -1  0]]


In [11]:
#Problem 9: vw
solution9 = v @ w
print("Problem 9 Solution:\n", solution9)

Problem 9 Solution:
 [[12]]


In [12]:
#Problem 10: w^Tv^T
solution10 = w.T @ v.T
print("Problem 10 Solution:\n", solution10)

Problem 10 Solution:
 [[12]]


In [13]:
#Problem 11: w^Tw
solution11 = w.T @ w
print("Problem 11 Solution:\n", solution11)

Problem 11 Solution:
 [[42]]


In [14]:
#Problem 12: vv^T
solution12 = v @ v.T
print("Problem 12 Solution:\n", solution12)

Problem 12 Solution:
 [[15]]


In [15]:
#Problem 13: vA
solution13 = v @ A
print("Problem 13 Solution:\n", solution13)

Problem 13 Solution:
 [[4 3 9]]


In [16]:
#Problem 14: AB
solution14 = A @ B
print("Problem 14 Solution:\n", solution14)

Problem 14 Solution:
 [[ 1  1  4  9]
 [ 3  1  7 17]
 [ 0  2  3  4]
 [ 0  0  2  6]]


In [17]:
#Problem 15: vAB
solution15 = v @ (A @ B)
print("Problem 15 Solution:\n", solution15)

Problem 15 Solution:
 [[ 7  1 21 57]]


In [18]:
#Problem 16: A^TA
solution16 = A.T @ A
print("Problem 16 Solution:\n", solution16)

Problem 16 Solution:
 [[6 1 3]
 [1 2 1]
 [3 1 6]]


In [19]:
#Problem 17: BB^T - A^TA
solution17 = (B @ B.T) - (A.T @ A)
print("Problem 17 Solution:\n", solution17)

Problem 17 Solution:
 [[41 11 18]
 [11  4  5]
 [18  5  4]]


In [20]:
#Problem 18: A * B^T
solution18 = A * B.T
print("Problem 18 Solution:\n", solution18)

Problem 18 Solution:
 [[ 1  0  0]
 [ 2 -1  0]
 [ 3  0  0]
 [ 0  0  6]]


In [21]:
#Problem 19: vector outer product(v^T w)
solution19 = np.outer(v.T, w)
print("Problem 19 Solution:\n", solution19)

Problem 19 Solution:
 [[ 5  4  1  0]
 [10  8  2  0]
 [-5 -4 -1  0]
 [15 12  3  0]]


In [22]:
#Problem 20: vector outer product(w v^T)
solution20 = np.outer(w, v.T)
print("Problem 20 Solution:\n", solution20)

Problem 20 Solution:
 [[ 5 10 -5 15]
 [ 4  8 -4 12]
 [ 1  2 -1  3]
 [ 0  0  0  0]]


<h2><u>Feedback</u></h2>

Great work. Exemplary submission. 🎉</br>

By Hand solution 50/50</br>

Detailed calculation process.</br>
All correct results.</br>
Python solution 50/50</br>

Well-organized and clear.</br>