In [47]:
import numpy as np

In [48]:
v = np.array([[1, 2, -1, 3]])
w = np.array([[5], 
              [4], 
              [1],
              [0]])
A = np.array([[1, 0, 1],
              [2, 1, 2],
              [1, -1, 0],
              [0, 0, 2]])
B = np.array([[1, 1, 3, 6],
              [1, -1, 0, 2],
              [0, 0, 1, 3]])


In [49]:
# Problem 1: v + v
solution1 = v + v
print("Problem 1 Solution:\n", solution1)

Problem 1 Solution:
 [[ 2  4 -2  6]]


In [50]:
#Problem 2: 2v
solution2 = 2 * v
print("Problem 2 Solution:\n", solution2)

Problem 2 Solution:
 [[ 2  4 -2  6]]


In [51]:
#Problem 3: v^T + w
solution3 = v.T + w
print("Problem 3 Solution:\n", solution3)

Problem 3 Solution:
 [[6]
 [6]
 [0]
 [3]]


In [52]:
#Problem 4: v + wT
solution4 = v + w.T
print("Problem 4 Solution:\n", solution4)

Problem 4 Solution:
 [[6 6 0 3]]


In [53]:
#Problem 5: v^T - w
solution5 = v.T - w
print("Problem 5 Solution:\n", solution5)

Problem 5 Solution:
 [[-4]
 [-2]
 [-2]
 [ 3]]


In [54]:
#Problem 6: w - v^T
solution6 = w - v.T
print("Problem 6 Solution:\n", solution6)

Problem 6 Solution:
 [[ 4]
 [ 2]
 [ 2]
 [-3]]


In [55]:
#Problem 7: v +2w^T
solution7 = v + (2 * w.T)
print("Problem 7 Solution:\n", solution7)

Problem 7 Solution:
 [[11 10  1  3]]


In [56]:
#Problem 8: v @ w^T
solution8 = v @ w.T
print("Problem 8 Solution:\n", solution8)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 4)